name: OnlineJudge Deployment

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 */6 * * *'  # 每6小时重启一次（防止超时）

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start OnlineJudge
        run: |
          docker-compose up -d
          sleep 300  # 保持5分钟（仅测试用）
          # 如果要长期运行，可以改成 `while true; do sleep 3600; done`
